"""
Workout session khatam hone par summary banata hai (calories, duration,
reps, form score) - jise user text file ke roop me download kar sakta hai.
"""

from datetime import datetime

# Rough MET (Metabolic Equivalent of Task) values - calorie estimate ke liye
MET_VALUES = {
    "Squat": 5.0,
    "Bicep Curl": 3.0,
}


def estimate_calories(exercise, elapsed_seconds, weight_kg=70):
    """
    Standard formula: Calories/min = (MET x 3.5 x weight_kg) / 200
    Ye ek approximate estimate hai, exact medical-grade calorie count nahi.
    """
    met = MET_VALUES.get(exercise, 4.0)
    minutes = max(elapsed_seconds, 0) / 60.0
    calories_per_min = (met * 3.5 * weight_kg) / 200.0
    return round(calories_per_min * minutes, 1)


def build_summary_text(exercise, mode, total_reps, good_reps, bad_reps,
                        form_score, elapsed_seconds, calories):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    minutes = int(elapsed_seconds // 60)
    seconds = int(elapsed_seconds % 60)

    lines = [
        "===== AI Gym Form Checker - Workout Summary =====",
        f"Date/Time      : {timestamp}",
        f"Exercise       : {exercise}",
        f"Mode           : {mode}",
        f"Duration       : {minutes}m {seconds}s",
        "-" * 50,
        f"Total Reps     : {total_reps}",
        f"Good Form Reps : {good_reps}",
        f"Bad Form Reps  : {bad_reps}",
        f"Form Score     : {form_score}%",
        f"Est. Calories  : {calories} kcal",
        "=" * 50,
        "Generated by AI Gym Form Checker",
    ]
    return "\n".join(lines)
